import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner/Banner";
import Card from "../components/Card/Card";
import CardList from "../components/Card/CardList";
import RecipeCollections from "../components/RecipeCollections/RecipeCollections";

const Home: NextPage = () => {
  return (
    <div className="grid gap-5">
      <Head>
        <title>Wok a Wish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Banner />
        <div className="divider"></div>
      </div>
      <div>
        <p className="text-2xl font-semibold mb-6">Our Latest Recipes</p>
        <CardList />
      </div>
      <div className="bg-light-200 border-none mt-5 p-4">
      <p className="text-2xl font-semibold mb-6">Recipe Collections</p>
      <RecipeCollections/>
      </div>
    </div>
  );
};

export default Home;
